steps:
  - name: 'eclipse-temurin:17-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd projects/crypto-autotrading-app
        ./gradlew clean shadowJar --no-daemon
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/crypto-autotrading-lab/crypto-autotrading-lab/crypto-autotrading-lab:${_SHORT_SHA}'
      - '-f'
      - 'docker/app/Dockerfile'
      - '.'
images:
  - 'asia-northeast1-docker.pkg.dev/crypto-autotrading-lab/crypto-autotrading-lab/crypto-autotrading-lab:${_SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
