version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
    container_name: crypto-autotrading
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/app/data
      - APP_CONFIG_PATH=/app/config/application-gmo.yaml
      - API_BASE_URL=${API_BASE_URL:-https://api.coin.z.com}
      - GMO_PRIVATE_API_BASE_URL=${GMO_PRIVATE_API_BASE_URL:-http://wiremock:8080}
    volumes:
      - ../../config:/app/config
      - ../../data:/app/data
    depends_on:
      - wiremock

  wiremock:
    image: wiremock/wiremock:latest
    container_name: crypto-autotrading-wiremock
    ports:
      - "8080:8080"
    volumes:
      - ../../mocks/wiremock:/home/wiremock
    command: ["--global-response-templating", "--disable-gzip"]
